FROM nginx
COPY ./src/nginx-ssl/nginx.conf /etc/nginx/nginx.conf
COPY ./src/nginx-ssl/secure_server.crt /etc/nginx/secure_server.crt
COPY ./src/nginx-ssl/secure_server.key /etc/nginx/secure_server.key
